---
title: "山雨欲来风满楼"
author: "Frida Gomam"
date: 2019-04-24
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---
#2019年4月24日-4月28日小记
     

      ♥2019年04-24（星期三）

  本周两门专业课都没有布置课堂作业，课业压力相对较轻。不过亦有新的事情来填补时间上的相对清闲：准备周日晚的比赛以及关注暑期社会实践相关动态。
  
  周日晚的比赛是之前报名的四川大学“芙蕖杯”诗词大赛，自己充其量算个业余的诗词爱好者。前两个星期的某天下午，路过青春广场，偶然看到这个比赛的巨幅宣传海报横立路侧，有点心动又很是犹豫。晚上回到寝室纠结了许久，最后抱着认清自己的诗词水平和观赏诗词大佬们大显身手的决心报名了该活动。有幸通过了初赛，组了队，为决赛做准备。于是便开启了时时刻刻碎碎念的模式，背诗、听诗、抄诗成了每日的必修课。往往是一边感叹于诗词之美一边汗颜于自己的才疏学浅，担心自己拖团队的后腿。至于暑期社会实践，学校某个社团组织了好几个实践项目，和同学不停浏览各个项目的具体内容和要求，想选择一个自己感兴趣并且能胜任的项目。
  
  然后是，互联网分析与治理的课堂，老师一番神仙操作，在同学们目不暇接之时，淡然完成了个人网站搭建。而我Rstudio下了又卸，卸了又下，反反复复不下五次，愣是一次都没能打开，看着老师靓丽的网站，小沈流下了卑微的泪水......

    ♥2019-04-25（星期四）
    
今天依旧是背诗背到昏天黑地的一天呢

早上英语课表演小组舞台剧，台词流畅地背出来啦~只是肢体动作和眼神交流依旧显得僵硬，小沈要继续加油呀！

下午在炎炎烈日下上排球课，很热很累但是越打越有劲儿哈哈哈（虽然大多数时候在追逐四处飞扬的排球，但是运动真的很有趣呀）

第N次运行Rstudio失败...

    ♥2019-04-26（星期五）

疯狂背诗进行时（说句实话，再感兴趣的东西在短时间大量“摄入”真的会引起不适。比如现在的我，大量突击背诗巩固基础到一定阶段内心会有了点抵触，变成了一个没有感情的背诗机器。还是想回到平时那种兴致来了读读诗、背背词，细嚼慢咽，安定内心。不过既然决定了要去比赛现场长长见识，还是得疯狂“补课”的
晚上填写了文化行者项目报名表 
继续为Rstudio挣扎，最终在24：00左右，在机智室友的指导下，进行一番尝试和调整，成功打开Rstudio，good~

    ♥2019-04-27（星期六）
    
7：30起床去看了明晚比赛的彩排，进度有点缓慢，排了仨小时才进行到第一环节，到了饭点就离开了，回去继续背诗
下午，天阴沉了下来，狂风乍起，真真有一种“山雨欲来风满楼”之势。傍晚参加了之前报名项目的面试，状态不佳、经验不足和10：1的录取比例，小沈止步于一面，回到寝室后不久，大雨倾盆而下。


    ♥2019-04-28（星期日）
    
下午排球考试考发球，小沈和她的球友舍弃了午觉时间来到排球场练习发球。然后通过了考试。然后，小沈和她的室友变成了忙碌的捡球员，足球场、篮球场、乒乓球场、排球场，只要有排球飞到的地方，就有脚步匆匆的小沈和她的室友。然而，天公不作美，一颗颗排球顺着大风到处“洒落”，各个场地的排球是捡之不尽，扔之又来。最终，小沈和室友的排球追逐战以老师的下课哨声宣告结束。

晚上，早早到了决赛现场，等待比赛开始，最后的结果是，小沈和她的队友与其他十一支队伍止步于第一轮。小沈对自己没有什么惋惜的，因为确实自己只是个业余爱好者，诗词储备不足，被问到的问题确实是知识盲区，便，败了。反正是来享受过程的，不过整个活动的过程让小沈有些心有不甘。因为主办方对活动的组织程度瑕疵有点多，就第一环节而言每一个队被问到的问题难易程度不一致，甚至出现了彩排时用过的题，就公平性而言是有待商榷的。参加决赛的大家都很优秀，最后进入12强的各个组的表现也很精彩，有些选手的表现也诚然令人叹服。不过有点遗憾的是，因为第一轮的问题设置稍显不合理吧，说是考查实力却更像是考查运气，有些自己接触过的确实很有实力的小组或者个人因为运气不佳被过滤掉了，挺为她们不平的。

就自身而言的话，自己还是挺珍惜这次比赛的，它确实在一定程度上让我认清了自己的诗词水平，各位优秀选手的精彩表现也着实让我向往。更重要的是，和一群有着同样爱好的人为了同一个目标在一个平台上不带目的地畅聊爱好、互相学习、互相坚定，让我有了更坚定自己爱好的信心和勇气！

小沈冲鸭~

