---
title: 我的时间函数
author: zz
date: '2019-05-22'
slug: time
categories:
  - R
tags: []
---
#想要为感兴趣的历史人物做一个简单的时间函数

            ♥先从苏轼开始吧
"苏东坡是一个无可救药的乐天派、一个伟大的人道主义者、一个百姓的朋友、一个大文豪、大书法家、创新的画家、造酒试验家、一个工程师、一个憎恨清教徒主义的人、一位瑜伽修行者佛教徒、巨儒政治家、一个皇帝的秘书、酒仙、厚道的法官、一位在政治上专唱反调的人。一个月夜徘徊者、一个诗人、一个小丑。但是这还不足以道出苏东坡的全部……苏东坡比中国其他的诗人更具有多面性天才的丰富感、变化感和幽默感，智能优异，心灵却像天真的小孩——这种混合等于耶稣所谓蛇的智慧加上鸽子的温文。"   
                                                                      ----林语堂
                                                                      
                                                                      
```{r}
x<-Sys.Date()
y<-as.Date("1037-01-08")
x1<-as.numeric(format(x,"%Y"))
y1<-as.numeric(format(y,"%Y"))
y3<-as.Date("1056-01-01")
y4<-as.numeric(format(y3,"%Y"))
y5<-as.Date("1080-01-01")
y6<-as.numeric(format(y5,"%Y"))
y7<-as.Date("1101-01-01")
y8<-as.numeric(format(y7,"%Y"))

print(paste("今天是苏轼诞生",x1-y1,"周年"))
```


```{r,echo=FALSE,eval=TRUE}

w<-round(difftime(x,y,units="weeks"))
print(paste("今天是苏轼诞生",w,"周"))

d<-round(difftime(x,y,units="days"))
print(paste("今天是苏轼诞生",d,"天"))

h<-round(difftime(x,y,units="days"))
print(paste("苏轼诞生于",h,"小时之前"))

m<-round(difftime(x,y,units="mins"))
print(paste("苏轼诞生于",m,"分钟之前"))

s<-round(difftime(x,y,units="secs"))
print(paste("苏轼诞生于",s,"秒之前"))
```


```{r}
print(paste("公元",y1,"年，苏东坡出生在四川眉山。传说，就在这一年，眉山一座原本郁郁葱葱的大山，不知为何，突然花草凋零、树木枯萎。民间有言：”眉山出三苏，草木为之枯"))
```




```{r,echo=FALSE,eval=TRUE}
print(paste("公元",y4,"年，即北宋嘉祐元年春天，苏轼和弟弟苏辙在父亲苏洵陪伴下，离家出川，前往汴京参加科考.阴差阳错之下成为次年科考第二名"))

print(paste("公元",y6,"年，即北宋元丰三年，因卷入“乌台诗案”，苏轼遭贬黄州，而后被一贬再贬。这是苏轼仕途之“落”,际遇之悲，但我们的苏子向来不是因时运不齐而垂头丧气之人，正是在黄州，有了“竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生”，有了“突然浪起，掀舞一叶白头翁”，有了“人生如梦，一樽还酹江月”，降下了官阶，却升起了千古词人苏东坡。"))

print(paste("公元",y8,"年，即北宋亡国之君宋徽宗建中靖国元年，苏轼抱病卒于常州。那个生性放达、为人率真、好交友、好美食、好品茗，亦雅好游山林的苏子，作别了世间，慢慢隐入时间的画卷。斯人已逝，但其传达出的那份独一无二的精神品质从未败于岁月，而是时时刻刻在诸多国人心中闪耀。有人说，李白是仙，不染烟火于人间，而苏轼从始至终都在人间。不论岁月如何流转，他始终被时光记挂着，只因为他是苏子，是在人间行走的苏东坡。"))

```

#一个粗糙的表（还没学会怎么制表）

```{r}
x<-as.character("苏轼诞生眉州")
y<-as.character("苏轼出川赴考")
z<-as.character("苏轼被贬黄州")
f<-as.character("苏轼溘然长逝")
time<-c(1037,1056,1080,1101)
age<-c(1,21,45,66)
event<-c(x,y,z,f)
patientdata<-data.frame(time,age,event)
patientdata
```



